# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn verify -Pqa
    - name: 'Output Apex Tests Execution results'
      id: "apex-tests"
      run: |
        text=$(cat ./src/test/resources/asdf.txt)
        echo $text  
        echo "::set-output name=text::$text"  
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        run: |
         export SLACK_MESSAGE= $(cat ./src/test/resources/asdf.txt)
        SLACK_CHANNEL: general
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48 
        SLACK_TITLE: Automation scenarios test run
        SLACK_USERNAME: Krishna-autobot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  
